### ISSUE TITLE
第一次成功，再次拉全部内容的时候报错了

### ISSUE THREAD

**Issue by hongtoushizi** [chunxingque/youdaonote-pull#16]
本次使用 Cookies 登录
2024/11/13 17:44:48  INFO pull_notes.py:349 <module>   : 网络错误，请检查网络是否正常连接。若突然执行中断，可忽略此错误，重新运行脚本
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1123)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='note.youdao.com', port=443): Max retries exceeded with url: /yws/api/personal/file?method=getByPath&keyfrom=web&cstk=42CzZRMX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pull_notes.py", line 336, in <module>
    ydnote_dir_id, error_msg = youdaonote_pull.get_ydnote_dir_id()
  File "pull_notes.py", line 71, in get_ydnote_dir_id
    return self._get_ydnote_dir_id()
  File "pull_notes.py", line 141, in _get_ydnote_dir_id
    root_dir_info = self.youdaonote_api.get_root_dir_info_id()
  File "/Users/yuanhongshuai/python_work/youdaonote-pull/core/youDaoNoteApi.py", line 98, in get_root_dir_info_id
    return self.http_post(self.ROOT_ID_URL.format(cstk=self.cstk), data=data).json()
  File "/Users/yuanhongshuai/python_work/youdaonote-pull/core/youDaoNoteApi.py", line 79, in http_post
    return self.session.post(url, data=data, files=files)
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yuanhongshuai/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='note.youdao.com', port=443): Max retries exceeded with url: /yws/api/personal/file?method=getByPath&keyfrom=web&cstk=42CzZRMX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1123)')))
2024/11/13 17:44:48  INFO pull_notes.py:351 <module>   : 已终止执行

**Comment by chunxingque** [comment]
我测试了一下，目前拉取是正常的，应该是网络问题哦，你检查一下网络；或者说是可能是被有道云限制了，我还没遇到这种情况，你可以过两天再试一下。

**Comment by chunxingque** [comment]
我测试了一下，目前拉取是正常的，应该是网络问题哦，你检查一下网络；或者说是可能是被有道云限制了，我还没遇到这种情况，你可以过两天再试一下。
